### ISSUE TITLE
OpenBMC: Find 'If ... Else' statements and modify it with 'If ... ELSE'

### ISSUE THREAD

**Issue by prkatti1** [openbmc/openbmc-test-automation#1710] opened 2019-03-29 07:23 UTC
Wherever 'If Else' statements used. modify 'Else', and 'else' with ELSE.
Although robot is not case sensitive, in case of 'if ... else', else must be in capital letters in order for it to work. Otherwise else part won't work.
1. Search all tests where If Else used, make sure ELSE is in capital
2. Search all libraries where  If Else used, make sure ELSE is in capital

**Comment by sivassrr** [comment] 2019-03-29 08:20
Thank you for opening this issue. Was not aware that you also planned to open one.  :)
Will close this as duplicate of https://github.com/openbmc/openbmc-test-automation/issues/1709

And as explained earlier, Also opened issue in robotframework.

**Closed by sivassrr** 2019-03-29 08:20 UTC

**Comment by prkatti1** [comment] 2019-03-29 08:35
Sure @sivassrr , thanks.
