### ISSUE TITLE
lib/bmc_redfish_utils.py  __init__ create a redfish session, but not logout

### ISSUE THREAD

**Issue by Nevermore1849** [openbmc/openbmc-test-automation#2214] opened 2023-09-12 02:59 UTC
When I Use:

Library         bmc_redfish_utils.py  WITH NAME  redfish_utils

This will create a bmc_redfish_utils instance, and use __init__ method to verify redfish interface.

But its not logout after execute.
![image](https://github.com/openbmc/openbmc-test-automation/assets/49224652/2dd76d60-ff8a-47bb-b5dd-6f5ab90fbd02)

So when i execute all cases, I find some extra sessions in my web UI.

I modify this file like this now:
![image](https://github.com/openbmc/openbmc-test-automation/assets/49224652/056c4352-39e3-4a40-b9e4-73a0580b8d8d)

**Comment by gkeishin** [comment] 2023-09-15 08:28
@adathatri can u respond to this query ?

**Comment by adathatri** [comment] 2023-09-15 08:50
The issue is that the existing code is leaving logged in sessions without cleaning them up. 
@tester-noob Can you please push your changes to the repository and then we can take it from there. Thanks.

**Comment by SrideviRamesh** [comment] 2023-09-15 09:05
What if the user does not want to logout immediately. Should we provide an optional parameter/Flag if logout is required or not ?

**Comment by tester-noob** [comment] 2023-09-15 09:52
> The issue is that the existing code is leaving logged in sessions without cleaning them up. @tester-noob Can you please push your changes to the repository and then we can take it from there. Thanks.

I create a pull requests and commit my changes now. Isn't that okay

**Comment by adathatri** [comment] 2023-09-15 11:00
> > The issue is that the existing code is leaving logged in sessions without cleaning them up. @tester-noob Can you please push your changes to the repository and then we can take it from there. Thanks.
> 
> I create a pull requests and commit my changes now. Isn't that okay

Can you share the link? The changes should be pushed to the repo in Gerrit- https://gerrit.openbmc.org/q/project:openbmc%252Fopenbmc-test-automation

**Comment by adathatri** [comment] 2023-09-15 11:24
> What if the user does not want to logout immediately. Should we provide an optional parameter/Flag if logout is required or not ?

The framework is designed in such a way that an exclusive login and logout is required in the test suite. This code is just to check the response and should not be relied for any other use case. So logging out looks good here.

**Comment by Nevermore1849** [comment] 2023-09-18 05:14
> > > The issue is that the existing code is leaving logged in sessions without cleaning them up. @tester-noob Can you please push your changes to the repository and then we can take it from there. Thanks.
> > 
> > 
> > I create a pull requests and commit my changes now. Isn't that okay
> 
> Can you share the link? The changes should be pushed to the repo in Gerrit- https://gerrit.openbmc.org/q/project:openbmc%252Fopenbmc-test-automation

https://gerrit.openbmc.org/c/openbmc/openbmc-test-automation/+/66632

**Comment by gkeishin** [comment] 2023-09-18 16:38
@Nevermore1849 

For any code changes to get merged,  
```
OpenBMC contributors are required to execute an OpenBMC CLA (Contributor License Agreement) 
before their contributions can be accepted.
```
I don't see you are listed in the CLA here
https://drive.google.com/drive/folders/1Ooi0RdTcaOWF1DWFJUAJDdN7tRKde7Nl

Can you point me out if you are already part of it. If you are new, take a look at this one-time process https://github.com/openbmc/docs/blob/master/CONTRIBUTING.md#starting-out

**Comment by gkeishin** [comment] 2023-10-06 04:36
Please let us know if we need any new information before we close this ticket. Thanks

**Closed** 2023-10-09 03:37 UTC
