### ISSUE TITLE
PreTag: [System - barreleye Build - 20160610155319 ]  Set PowerCap

### ISSUE THREAD

**Issue by williamspatrick** [openbmc/openbmc-test-automation#26] opened 2016-06-17 11:51 UTC
@gkeishin commented on [Mon Jun 13 2016](https://github.com/openbmc/openbmc/issues/322)

One of the test case is looking for SetValue object... This object is not found as per the log ..

Can someone look into it and let us know.. why this is not available.. Thanks

For Reference log:

Start / End / Elapsed: 	20160613 12:31:25.747 / 20160613 12:31:25.747 / 00:00:00.000
12:31:25.747 	INFO 	${msg} = URI:https://9.3.23.30/org/openbmc/sensors/host/PowerCap/action/setValue, method:Post, args:{u'data': {u'data': [0]}, u'headers': {u'Content-Type': u'application/json'}} 	
00:00:00.001 KEYWORD rest_client . Logging ${msg}, console=TRUE

12:31:26.869 	INFO 	${resp} = <Response [404]> 	
12:31:26.870 	INFO 	${resp} = <Response [404]>

Documentation: 	

Fails if objects are unequal after converting them to strings.
Start / End / Elapsed: 	20160613 12:31:26.870 / 20160613 12:31:26.872 / 00:00:00.002
12:31:26.871 	INFO 	Argument types are:
<type 'int'>
<type 'unicode'> 	
12:31:26.872 	FAIL 	404 != 200

**Comment by gkeishin** [comment] 2016-08-24 17:12
We no longer see this issue.. but now seeing a different type of connection related issues

ConnectionError: HTTPSConnectionPool(host='9.3.29.119', port=443): Max retries exceeded with url: /login (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7ffff07437d0>: Failed to establish a new connection: [Errno 111] Connection refused',))

**Comment by gkeishin** [comment] 2016-09-08 13:24
We are seeing the powercap setting errors now frequently. 
Tests . Test Generic Conf
	7	4	3	00:00:41	

out of 7 , 3 are failing

 /org/openbmc/settings/host0, power_cap
1. Set the power with string of characters  (abcdefg)
2. Set the power with greater then MAX_POWER_VALUE  (1010)

/org/openbmc/settings/host0, boot_flags
1. Set the boot flags with string  ( 3ab56f  )

**Comment by anoo1** [comment] 2016-09-12 14:01
The power cap value was eventually implemented in the sensors path after the placeholder in the settings file was created.
We should determine if the power cap should be in 2 places and synced (sensors and settings), or just one place and remove the redundant one.

**Comment by gkeishin** [comment] 2016-09-12 14:23
@anoo1   Closing this one.. since this is not an automation related fix required..  There is opened on https://github.com/openbmc/openbmc/issues/557

Closing this...  Probably if you can comment in #557   .. Thanks

**Closed by gkeishin** 2016-09-12 14:23 UTC
