### ISSUE TITLE
FFDC to collect PLDM strace log ?

### ISSUE THREAD

**Issue by gkeishin** [openbmc/openbmc-test-automation#2158] opened 2022-02-02 08:51 UTC
```
strace -p `pidof pldmd`
```
Ideally, this needs to be collected in the event when PLDM hung, but the log collector won't have that logic to check.. 

so if we can collect this one? run the command and then CTRL +C after 5-10 seconds 

@peterp-ibm  can u check on it.

**Comment by gkeishin** [comment] 2022-02-02 09:20
Probably not a good idea to put this in for generic log collection. only on failure.. but lets see if we can learn something from it to improve the script

**Comment by peterp-ibm** [comment] 2022-02-16 11:30
To get strace output need to use option '-o' or pipe stderr to a file
strace -p $(pidof pldmd) -o /tmp/pldmd.txt
strace -p $(pidof pldmd) 2> /tmp/pldmd.txt


Now the issue is how to interrupt/stop strace without ffdc code having to look at the command itself.

**Comment by peterp-ibm** [comment] 2022-03-03 11:05
Done! https://gerrit.openbmc-project.xyz/c/openbmc/openbmc-test-automation/+/51705
Committed for review and merge.

**Closed** 2022-03-03 13:15 UTC
